"use client";

import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { QrCode, ArrowLeft, ArrowRight } from "lucide-react";
import axiosClient from "@/lib/axiosClient";
import { Eye, EyeOff } from "lucide-react";

export default function SignUpPage() {
  const router = useRouter();
  const [currentStep, setCurrentStep] = React.useState(1);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState("");
  const [showPassword, setShowPassword] = React.useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = React.useState(false);

  const [formData, setFormData] = React.useState({
    name: "",
    email: "",
    password: "",
    password_confirmation: "",
    agreeToTerms: false,
    organization: {
      name: "",
      slug: "",
      description: "",
    },
  });

  // Generate slug from organization name
  const generateSlug = (name: string) => {
    return name
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_-]+/g, "-")
      .replace(/^-+|-+$/g, "");
  };

  // Handle organization name change and auto-generate slug
  const handleOrganizationNameChange = (name: string) => {
    const slug = generateSlug(name);
    setFormData({
      ...formData,
      organization: {
        ...formData.organization,
        name,
        slug: formData.organization.slug || slug, // Only auto-fill if slug is empty
      },
    });
  };

  // Validate Step 1 (User Details)
  const validateStep1 = () => {
    const { name, email, password, password_confirmation, agreeToTerms } = formData;

    if (!name || !email || !password || !password_confirmation) {
      setError("All fields are required.");
      return false;
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      setError("Please enter a valid email address.");
      return false;
    }

    if (password.length < 8) {
      setError("Password must be at least 8 characters long.");
      return false;
    }

    if (password !== password_confirmation) {
      setError("Password and Confirm Password do not match.");
      return false;
    }

    if (!agreeToTerms) {
      setError("Please agree to the terms and conditions.");
      return false;
    }

    return true;
  };

  // Validate Step 2 (Organization Details)
  const validateStep2 = () => {
    const { organization } = formData;

    if (!organization.name) {
      setError("Organization name is required.");
      return false;
    }

    if (organization.name.length > 255) {
      setError("Organization name must be less than 255 characters.");
      return false;
    }

    if (organization.slug && organization.slug.length > 255) {
      setError("Organization slug must be less than 255 characters.");
      return false;
    }

    return true;
  };

  // Handle Next Step
  const handleNext = () => {
    setError("");
    if (currentStep === 1 && validateStep1()) {
      setCurrentStep(2);
    }
  };

  // Handle Back Step
  const handleBack = () => {
    setError("");
    setCurrentStep(1);
  };

  // Handle Final Submit
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    
    if (!validateStep2()) {
      return;
    }

    setLoading(true);

    try {
      const { name, email, password, password_confirmation, organization } = formData;

      // Prepare organization data
      const orgData: any = {
        name: organization.name,
      };

      // Add slug if provided, otherwise it will be auto-generated by backend
      if (organization.slug) {
        orgData.slug = organization.slug;
      }

      // Add description if provided
      if (organization.description) {
        orgData.description = organization.description;
      }

      const res = await axiosClient.post("/auth/register", {
        name,
        email,
        password,
        password_confirmation,
        organization: orgData,
      });

      // Store token if provided
      if (res.data?.data?.access_token) {
        localStorage.setItem("token", res.data.data.access_token);
      }

      // Store user data if provided
      if (res.data?.data?.user) {
        localStorage.setItem("user", JSON.stringify(res.data.data.user));
      }

      alert("Signup successful! Please verify your email.");
      router.push("/signin");

    } catch (err: any) {
      console.error("Signup error:", err);

      if (err.response?.status === 422) {
        const errors = err.response.data.errors as Record<string, string[]>;
        const errorMessages: string[] = [];
        
        // Collect all error messages
        Object.keys(errors).forEach((key) => {
          errors[key].forEach((msg: string) => {
            errorMessages.push(msg);
          });
        });
        
        setError(errorMessages.join(". ") || "Validation error occurred.");
      } else {
        setError(err.response?.data?.message || "Something went wrong. Try again.");
      }
    } finally {
      setLoading(false);
    }
  };
  
  
  const handleSocialSignup = (provider: string) => {
    console.log(`[v0] Sign up with ${provider}`);
    router.push("/dashboard");
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-blue-50 via-white to-purple-50 p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="space-y-1 text-center">
          <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-blue-100">
            <QrCode className="h-6 w-6 text-blue-600" />
          </div>
          <CardTitle className="text-2xl font-bold">Create an account</CardTitle>
          <CardDescription>
            Get started with EngageIQ today - no credit card required
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-4">
          {/* Progress Indicator */}
          <div className="space-y-2">
            <div className="flex items-center justify-between text-sm text-muted-foreground mb-2">
              <span className={currentStep >= 1 ? "font-medium text-blue-600" : ""}>
                Step 1: Your Details
              </span>
              <span className={currentStep >= 2 ? "font-medium text-blue-600" : ""}>
                Step 2: Organization
              </span>
            </div>
            <Progress value={(currentStep / 2) * 100} className="h-2" />
          </div>

          {/* Error Message */}
          {error && (
            <div className="rounded-md bg-red-50 p-3">
              <p className="text-red-600 text-sm">{error}</p>
            </div>
          )}

          {/* Social Signup Buttons - Only show on step 1 */}
          {/*{currentStep === 1 && (
            <>
              <div className="grid gap-2">
                <Button
                  variant="outline"
                  onClick={() => handleSocialSignup("google")}
                  className="w-full"
                >
                  Sign up with Google
                </Button>

                <Button
                  variant="outline"
                  onClick={() => handleSocialSignup("linkedin")}
                  className="w-full"
                >
                  Sign up with LinkedIn
                </Button>
              </div>

              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <Separator />
                </div>
                <div className="relative flex justify-center text-xs uppercase">
                  <span className="bg-card px-2 text-muted-foreground">
                    Or continue with email
                  </span>
                </div>
              </div>
            </>
          )}*/}

          {/* Step 1: User Details Form */}
          {currentStep === 1 && (
            <form onSubmit={(e) => { e.preventDefault(); handleNext(); }} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="name">Full Name</Label>
                <Input
                  id="name"
                  type="text"
                  placeholder="John Doe"
                  value={formData.name}
                  onChange={(e) =>
                    setFormData({ ...formData, name: e.target.value })
                  }
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="you@example.com"
                  value={formData.email}
                  onChange={(e) =>
                    setFormData({ ...formData, email: e.target.value })
                  }
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <div className="relative">
                  <Input
                    id="password"
                    type={showPassword ? "text" : "password"}
                    placeholder="••••••••"
                    value={formData.password}
                    onChange={(e) =>
                      setFormData({ ...formData, password: e.target.value })
                    }
                    required
                    className="pr-10"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                  >
                    {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>
                <p className="text-xs text-muted-foreground">
                  Must be at least 8 characters long
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="password_confirmation">Confirm Password</Label>
                <div className="relative">
                  <Input
                    id="password_confirmation"
                    type={showConfirmPassword ? "text" : "password"}
                    placeholder="••••••••"
                    value={formData.password_confirmation}
                    onChange={(e) =>
                      setFormData({ ...formData, password_confirmation: e.target.value })
                    }
                    required
                    className="pr-10"
                  />
                  <button
                    type="button"
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                  >
                    {showConfirmPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="terms"
                  checked={formData.agreeToTerms}
                  onCheckedChange={(checked) =>
                    setFormData({
                      ...formData,
                      agreeToTerms: checked as boolean,
                    })
                  }
                />
                <label
                  htmlFor="terms"
                  className="text-sm leading-none"
                >
                  I agree to the{" "}
                  <Link href="/terms" className="text-blue-600 hover:underline">
                    Terms of Service
                  </Link>{" "}
                  and{" "}
                  <Link
                    href="/privacy"
                    className="text-blue-600 hover:underline"
                  >
                    Privacy Policy
                  </Link>
                </label>
              </div>

              <Button
                type="submit"
                className="w-full bg-blue-600 hover:bg-blue-700"
              >
                Next: Organization Details
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </form>
          )}

          {/* Step 2: Organization Details Form */}
          {currentStep === 2 && (
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="org_name">Organization Name *</Label>
                <Input
                  id="org_name"
                  type="text"
                  placeholder="Acme Corporation"
                  value={formData.organization.name}
                  onChange={(e) => handleOrganizationNameChange(e.target.value)}
                  required
                />
                <p className="text-xs text-muted-foreground">
                  The name of your organization
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="org_slug">Organization Slug</Label>
                <Input
                  id="org_slug"
                  type="text"
                  placeholder="acme-corp"
                  value={formData.organization.slug}
                  onChange={(e) =>
                    setFormData({
                      ...formData,
                      organization: {
                        ...formData.organization,
                        slug: e.target.value,
                      },
                    })
                  }
                />
                <p className="text-xs text-muted-foreground">
                  Optional. A URL-friendly identifier (auto-generated from name if not provided)
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="org_description">Description</Label>
                <Textarea
                  id="org_description"
                  placeholder="A leading technology company"
                  value={formData.organization.description}
                  onChange={(e) =>
                    setFormData({
                      ...formData,
                      organization: {
                        ...formData.organization,
                        description: e.target.value,
                      },
                    })
                  }
                  rows={3}
                />
                <p className="text-xs text-muted-foreground">
                  Optional. A brief description of your organization
                </p>
              </div>

              <div className="flex gap-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleBack}
                  className="flex-1"
                >
                  <ArrowLeft className="mr-2 h-4 w-4" />
                  Back
                </Button>
                <Button
                  type="submit"
                  disabled={loading}
                  className="flex-1 bg-blue-600 hover:bg-blue-700"
                >
                  {loading ? "Creating Account..." : "Create Account"}
                </Button>
              </div>
            </form>
          )}
        </CardContent>

        <CardFooter className="flex justify-center">
          <p className="text-sm text-muted-foreground">
            Already have an account?{" "}
            <Link href="/signin" className="font-medium text-blue-600 hover:underline">
              Sign in
            </Link>
          </p>
        </CardFooter>
      </Card>
    </div>
  );
}
